[package]
name = "rectangle_simple_buffer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wit-bindgen.workspace = true
bytemuck = "1"

[lib]
crate-type = ["cdylib"]
