package example:example;

/// wit for the examples in this repo
world example {
    include wasi:webgpu/imports;
    include wasi:surface/imports;
    include wasi:graphics-context/imports;
    include wasi:frame-buffer/imports;

    /// main entrypoint
    export start: func();

    /// print to stdout
    import print: func(s: string);
}
