package example:example;

/// wit for the examples in this repo
world example {
    include wasi:webgpu/imports;

    /// main entrypoint
    export start: func();

    /// print to stdout
    import print: func(s: string);
}
