package component:webgpu;

/// wit for the examples in this repo
world example {
  import webgpu;

  /// main entrypoint
  export start: func();

  /// print to stdout
  import print: func(s: string);
}
