name: CI

on:
  push:
    branches: ["*"]
    tags: [v0.*]
  pull_request:
  merge_group:

jobs:
  check:
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - name: Linux x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            kind: native

    name: Clippy ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Workspace Check
        run: cargo check --workspace
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets


